.appveyor.yml, .travis.yml, README.md, doc/FAQ.rst, doc/README.md, doc/about.rst, doc/conf.py, doc/index.rst, dodo.py, environment.yml, examples/user_guide/Placeholder.ipynb
The purpose of this PR is to have website built automatically from notebooks.
For now, the website will be rebuilt for any commit to master (if this PR is merged). I guessed an examples/user_guide structure, but it can be changed. There's a placeholder notebook (examples/user_guide/Placeholder.ipynb), and the generated website will appear at https://pyviz.github.io/earthsim (if this PR is merged).
This PR also adds builds on linux, windows, and macos (master only, i.e. not on PRs, because of low travis/macos performance)
Notes:
* I've used doit so that editing the .travis/.appveyor files should not be necessary. Instead, you can add/edit commands and/or tasks in "dodo.py" (yes, that's the name, I didn't choose it). It's a bit like a makefile. I'm not deeply wedded to doit yet, so please …
=> Initial CI

.travis.yml, earthsim/annotators.py, earthsim/filigree.py, earthsim/gssha/__init__.py, earthsim/gssha/model.py, earthsim/io.py, earthsim/readers.py, environment.yml
As the title says, this migrates the code from the original (private) EarthSim repo.
=> Migrated code from original repo

dodo.py
See #12 (made the PR against the wrong branch and couldn't figure out how to change it in the github interface...)
=> Use nbsite conda packages.

dodo.py, environment.yml
This should fix doc building, but will need to merge to see that.
=> Ensure scipy+deps comes from c-f while we're using c-f

earthsim/filigree.py
Simple fix for https://github.com/pyviz/EarthSim/issues/39
=> Fixed bug clearing mesh

earthsim/annotators.py, earthsim/custom_tools.py, earthsim/custom_tools.ts
Adds two custom tools a CheckPointTool and a RestoreTool, the checkpoint tool makes a snapshot of the CDS data and pushes it onto a buffer and the RestoreTool pops off the buffer and restores the snapshot.
=> Added custom Checkpoint and Restore tools

earthsim/annotators.py, earthsim/custom_tools.py, earthsim/custom_tools.ts
Adds a custom ``ClearTool`` which allows resetting all drawn annotations.
=> Add custom ClearTool

earthsim/grabcut.py, examples/topics/GrabCut.ipynb
Various improvements for the GrabCut dashboard including:
* Allows setting the number of iterations to run the algorithm
* Default to Path type
* Add button to filter paths using simple array length of the path
=> Improved GrabCut dashboard

.travis.yml
=> Temporarily skip parameter sweep/batch notebooks from docs.

earthsim/annotators.py
=> Allow passing in elements to Annotator constructor

earthsim/annotators.py, earthsim/links.py
Adds a VertexTableLink to allow viewing, editing and annotating vertices of a polygon/path in JS. Much faster and more robust than the previous approach.
=> Added VertexTableLink to PolyAnnotator

dependencies.txt
Presumably no major changes since 1.5.2a5
=> Switch to geoviews 1.5.2 release.

earthsim/links.py
=> Ensure vertex table resets on deletion

doc/getting_started/index.rst, examples/user_guide/Annotators.ipynb, examples/user_guide/Drawing_Tools.ipynb
Clarified developer instructions as suggested in https://github.com/pyviz/EarthSim/issues/175
=> Clarified developer instructions

earthsim/annotators.py
=> Fixed bug in PolyAnnotator

earthsim/annotators.py
=> Fix for PolyEdit tool in PolyAnnotator

dependencies.txt, earthsim/__init__.py, earthsim/annotators.py, examples/user_guide/Specifying_Meshes.ipynb
=> Enable extent padding and unset default extent

dependencies-dev-overrides.txt, dependencies.txt, earthsim/links.py
=> Updated links for compatibility with holoviews master

earthsim/io.py
modified the 3dm reader to store the material types in the tris data frame instead of tossing this data.
=> added materials to 3dm reader

earthsim/links.py
Depends on https://github.com/ioam/holoviews/pull/3206 to have any actual effect
=> Fixes issues with Links to garbage collected objects

README.md
=> Updated README after move from pyviz to pyviz-topics

.travis.yml
Build for both dev and release tags
=> Make docs only build when tagging

dependencies.txt, earthsim/grabcut.py, earthsim/gssha/__init__.py, examples/topics/GSSHA_Parameter_Sweep.ipynb, examples/topics/GSSHA_Workflow.ipynb, examples/topics/batched_example/GSSHA_Workflow_Batched_Example1.ipynb, examples/topics/batched_example/GSSHA_Workflow_Batched_Example2.ipynb, examples/user_guide/Annotators.ipynb, examples/user_guide/WMTS_Example.ipynb, setup.py, tox.ini
I'm working on release a new version on Quest that this PR depends on. I'll mark it as ready once I get that released.
=> Quest updates

.travis.yml, earthsim/annotators.py, earthsim/links.py, earthsim/models/poly_draw.ts, earthsim/models/poly_edit.ts, setup.py
=> Tool UI fixes

doc/conf.py
@philippjfr @jlstevens 
I added the Google Analytics ID to the conf.py file.
=> Adding the google analytics ID
